[execution]
# Execution Configutation
parallel_pool_size = 1
independent_executions = 1

[experiment]
# Experiment Configuration
scheduled_time_ratio = [0.1, 0.5, 0.8]
#datasets_dir = "examples"
#datasets = ["fakedata"]

# WTS
#datasets_dir = "examples/core@dune-common"
#datasets = ["dune@total"]

# VTS
datasets_dir = "examples/core@dune-common"
datasets = ["dune@debian_10 clang-7-libcpp-17", "dune@debian_11 gcc-10-20", "dune@ubuntu_20_04 clang-10-20"]

experiment_dir = "results/experiments/"
rewards = ["RNFail", "TimeRank"]
#policies = ['Random', 'Greedy', 'EpsilonGreedy', 'UCB', 'FRRMAB']
policies = ['Random']

[algorithm.frrmab]
# Algorithm Configuration for FRRMAB
window_sizes = [100]
timerank = { c = 0.5 }
rnfail = { c = 0.3 }

[algorithm.ucb]
# Algorithm Configuration for UCB
timerank = { c = 0.5 }
rnfail = { c = 0.3 }

[algorithm.epsilongreedy]
# Algorithm Configuration for Epsilon-Greedy
timerank = { epsilon = 0.5 }
rnfail = { epsilon = 0.3 }

[hcs_configuration]
# HCS Configuration
wts_strategy = false