blank_issues_enabled: false
contact_links:
  - name: coleman4hcs Support
    url: https://github.com/jacksonpradolima/coleman4hcs
    about: |
      Please only file issues here if they relate to actual bugs or feature requests for the coleman4hcs project.
      For more general discussions or questions, open an issue and select the appropriate template.
